lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views --already done
    path('friends', friend_list, name='friend_list')
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views --already done
    path('xml/', xml, name='xml'),
    path('json/', json, name='json')
]

lab_3/urls.py
from django.urls import path
from .views import index, addFriendy

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views --already done
    path('add/', addFriendy, name='add')
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add_note'),
    path('note-list', note_list, name='note_list')
]

praktikum/urls.py
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from django.urls import path, re_path, include
from django.contrib import admin
import lab_1.urls as lab_1
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include(lab_1)),
    re_path(r'^$', index_lab1, name='index'),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    NPM = models.CharField(max_length=10)
    DOB = models.DateField()
    # TODO Implement missing attributes in Friend model -- already done

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    from_user = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    message = models.TextField()

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django.forms import ModelForm, fields
from lab_1.models import Friend


class FriendForm(ModelForm) :
    class Meta:
        model = Friend
        fields = "__all__"
        

lab_4/forms.py
from django import forms
from django.forms import ModelForm, fields
from lab_2.models import Note



class NoteForm(ModelForm) :
    class Meta:
        model = Note
        fields = "__all__"

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Yunia Harmulyati'  # TODO Implement this --done
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2003,6,27)  # TODO Implement this, format (Year, Month, Date) -done
npm = 2106750515 # TODO Implement this -done


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all() # TODO Implement this -done
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from lab_2.models import Note
from django.core import serializers
from django.http.response import HttpResponse
from lab_2.models import Note

# Create your views here.
def index(request):
    response = {"data" : Note.objects.all}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import render
from lab_1.models import Friend
from .forms import FriendForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all() # TODO Implement this -done
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def addFriendy(request):
    response = {}
    forms = FriendForm(request.POST or None)
    if request.method == "POST" :
        if forms.is_valid():
            forms.save()
            return HttpResponseRedirect('/lab-3')
    response['forms'] = forms
    return render(request,'lab3_forms.html', response)

lab_4/views.py
from django.shortcuts import render
from lab_2.models import Note
from lab_4.forms import NoteForm
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    response = {"data" : Note.objects.all}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    response = {}
    forms = NoteForm(request.POST or None)
    if request.method == "POST" :
        if forms.is_valid():
            forms.save()
            return HttpResponseRedirect('/lab-4')
    response['forms'] = forms
    return render(request,'lab4_form.html', response)

def note_list(request):
    response = {"data" : Note.objects.all}
    return render(request, 'lab4_note_list.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model - done --> 
      {% for i in friends %}
      <tr>
        <td>{{ i.name }}</td>
        <td>{{ i.NPM }}</td>
        <td>{{ i.DOB }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>to</th>
        <th>from</th>
        <th>title</th>
        <th>message</th>
      </tr>
      <!-- TODO loop from Friend model - done --> 
      {% for i in data %}
      <tr>
        <td>{{ i.to }}</td>
        <td>{{ i.from }}</td>
        <td>{{ i.title }}</td>
        <td>{{ i.message }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_3/templates/lab3_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lab 3 - PBP</title>
</head>
<body>
  <form action="" method="POST"> {% csrf_token %}
    Name: <p> <input type="text" name="name" maxlength="30" id="id_name"> </p>
    NPM: <p> <input type="text" name="NPM" maxlength="30" id="id_npm"> </p>
    Tanggal Lahir: <p> <input type="date" name="DOB" id="id_birth_date"> </p>
    <input type="submit" value="Submit">
</form>
</body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model - done --> 
      {% for i in friends %}
      <tr>
        <td>{{ i.name }}</td>
        <td>{{ i.NPM }}</td>
        <td>{{ i.DOB }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
      .main{
          padding: 20px;
      }
  </style>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Tugas Lab PBP</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light table-bordered">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Menu</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/lab-4">Friend List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="add-note">Add Friend</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="note-list">Friend's Card</a>
              </li>
              
            </ul>

          </div>
        </div>
        
      </nav>
      <div class="main">
      <form action="" method="POST"> {% csrf_token %}
        <div class="mb-3">
          <label for="to" class="form-label">🤎 ~ To :</label>
          <input type="text" name="to" class="form-control" id="to" placeholder="Ketik orang yang dituju disini . .">
        </div>

        <div class="mb-3">
            <label for="from" class="form-label">🤎 ~ From :</label>
            <input type="text" name="from_user" class="form-control" id="from_user" placeholder="Ketik nama disini . ." >
            <div id="userHelp" class="form-text">We'll never share your identity with anyone else.</div>
        </div>

        <div class="mb-3">
            <label for="title" class="form-label">🤎 ~ Title :</label>
            <input type="text" name="title" class="form-control" id="title" placeholder="Ketik judul disini . ." >
        </div>

        <div class="mb-3">
            <label for="message" class="form-label">🤎 ~ Message :</label>
            <input type="text" name="message" class="form-control" id="message" placeholder="Ketik pesan disini . .">
          </div>

        <button type="submit" value="Submit" class="btn btn-dark btn-outline-warning">Submit</button>
      </form>
    </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

lab_4/templates/lab4_index.html
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .main{
            padding: 30px
        }
    </style>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Tugas Lab PBP</title>
  </head>
  <body>
      
    <nav class="navbar navbar-expand-lg navbar-light bg-light table-bordered">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Menu</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/lab-4">Friend List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="add-note">Add Friend</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="note-list">Friend's Card</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
      <div class="main">

    
      <h3>~ 🤎 Your Friend List 🤎 ~</h3>
      <br>
      <table class="table table-striped table-hover table-bordered border-dark">
        <tr>
          <th>Title</th>
          <th>To</th>
          <th>From</th>
          <th>Message</th>
        </tr>
        <!-- TODO loop from Friend model - done --> 
        {% for i in data %}
        <tr>
          <td>{{ i.title }}</td>
          <td>{{ i.to }}</td>
          <td>{{ i.from_user }}</td>
          <td>{{ i.message }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .main{
            display: flex;
            flex-direction: row;
            padding: 20px;
            flex-wrap: wrap;
        }
        .wrapper{
            padding: 20px;
        }
    </style>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Tugas Lab PBP</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light table-bordered">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Menu</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/lab-4">Friend List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="add-note">Add Friend</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="note-list">Friend's Card</a>
              </li>
              
            </ul>
          </div>
        </div>
        
      </nav>

      
        <div class="main">
        {% for i in data %}
        <div class="wrapper">
        <div class="card text-dark bg-light border-dark" style="width: 18rem;">
            <img src="https://www.propertinews.id/content.images/content/1/4065/750/0/500" alt="Image Not Found">
            <div class="row3">
                <div class="card-body">
                <h5 class="card-title">{{i.title}}</h5>
                <ul class="list-group list-group-flush">
                    From : <li class="list-group-item">{{i.from_user}}</li>
                    To : <li class="list-group-item">{{i.to}}</li>
                </ul>
                Message : <p class="card-text">{{i.message}}</p>
              
              
            </div>
            </div>
                    </div>
        </div>
            {% endfor %}
        </div>

        
   



    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
  </body>
</html>